<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="Pages\Chairman\Admin\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="ViewModels\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Pages\Chairman\Admin\**" />
    <Content Remove="Services\**" />
    <Content Remove="ViewModels\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Pages\Chairman\Admin\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="Controllers\**" />
    <None Remove="Pages\Chairman\Admin\**" />
    <None Remove="Services\**" />
    <None Remove="ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Pages\Teacher\_TeacherSidebar.cshtml.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

</Project>
